import { CharacterData } from "../components/CharacterSheet";
export const INITIAL_DATA: CharacterData = {
  info: { name: "", alias: "", profession: "" },
  stats: { forza: 0, agilita: 0, spirito: 0, ingegno: 0 },
  skills: {
    prestanza: 0,
    resistenza: 0,
    rissa: 0,
    empatia: 0,
    intuizione: 0,
    percezione: 0,
    rituali: 0,
    movimento: 0,
    "armi-da-fuoco": 0,
    furtivita: 0,
    "gioco-di-mano": 0,
    medicina: 0,
    ingegneria: 0,
    investigazione: 0,
    occultismo: 0,
  },
  tracks: { maledetti: 0, salute: 0, stress: 0 },
  inventory: "",
  weapons: ["", "", ""],
  talents: Array(5).fill({ name: "", level: 0, page: 0 }),
};
